# Generated by Django 5.0.6 on 2024-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrationform_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=6),
        ),
    ]
